# Generated by Django 5.1.7 on 2025-03-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLOnlineAntrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('stud_email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('application_date_bafoeg', models.DateField(blank=True)),
                ('account_holder', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=100)),
                ('bic', models.CharField(max_length=100)),
                ('signed_form', models.FileField(upload_to='signed_forms/')),
                ('health_insurance_certificate', models.FileField(upload_to='health_insurance_certificates/')),
                ('enrollment_certificate', models.FileField(upload_to='enrollment_certificates/')),
                ('bank_statements', models.FileField(upload_to='bank_statements/')),
                ('identity_document', models.FileField(upload_to='identity_documents/')),
                ('other_documents', models.FileField(blank=True, upload_to='other_documents/')),
            ],
        ),
    ]
